/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as LinksRouteImport } from './routes/links'
import { Route as ParticularRouteImport } from './routes/particular'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApresentacoesIndexRouteImport } from './routes/apresentacoes.index'
import { Route as ApresentacoesInformaticaCreateRouteImport } from './routes/apresentacoes.informatica-create'
import { Route as ApresentacoesInformaticaJuniorRouteImport } from './routes/apresentacoes.informatica-junior'
import { Route as ApresentacoesTecnologiaCreateRouteImport } from './routes/apresentacoes.tecnologia-create'
import { Route as ApresentacoesTecnologiaJuniorRouteImport } from './routes/apresentacoes.tecnologia-junior'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosAcademiesRouteImport } from './routes/cursos.academies'
import { Route as CursosCampsRouteImport } from './routes/cursos.camps'
import { Route as CursosCreateRouteImport } from './routes/cursos.create'
import { Route as CursosJuniorRouteImport } from './routes/cursos.junior'
import { Route as ParticularIndexRouteImport } from './routes/particular.index'
import { Route as ProfessoresInformaticaCreateRouteImport } from './routes/professores.informatica-create'
import { Route as ProfessoresInformaticaJuniorRouteImport } from './routes/professores.informatica-junior'
import { Route as ProfessoresTecnologiaCreateRouteImport } from './routes/professores.tecnologia-create'
import { Route as ProfessoresTecnologiaJuniorRouteImport } from './routes/professores.tecnologia-junior'
import { Route as SobreIndexRouteImport } from './routes/sobre.index'
import { Route as SobreVisaoRouteImport } from './routes/sobre.visao'
import { Route as CursosCreateIndexRouteImport } from './routes/cursos.create.index'
import { Route as CursosCreate1011AnosRouteImport } from './routes/cursos.create.10-11-anos'
import { Route as CursosCreate1112AnosRouteImport } from './routes/cursos.create.11-12-anos'
import { Route as CursosCreate1213AnosRouteImport } from './routes/cursos.create.12-13-anos'
import { Route as CursosCreate1314AnosRouteImport } from './routes/cursos.create.13-14-anos'
import { Route as CursosCreate89AnosRouteImport } from './routes/cursos.create.8-9-anos'
import { Route as CursosCreate910AnosRouteImport } from './routes/cursos.create.9-10-anos'
import { Route as CursosJuniorIndexRouteImport } from './routes/cursos.junior.index'
import { Route as CursosJunior56AnosRouteImport } from './routes/cursos.junior.5-6-anos'
import { Route as CursosJunior67AnosRouteImport } from './routes/cursos.junior.6-7-anos'
import { Route as CursosJunior78AnosRouteImport } from './routes/cursos.junior.7-8-anos'
import { Route as ParticularCursosAdsRouteImport } from './routes/particular.cursos.ads'
import { Route as ParticularCursosAgentesIaRouteImport } from './routes/particular.cursos.agentes-ia'
import { Route as ParticularCursosAutocadRouteImport } from './routes/particular.cursos.autocad'
import { Route as ParticularCursosBackendRouteImport } from './routes/particular.cursos.backend'
import { Route as ParticularCursosCanvaRouteImport } from './routes/particular.cursos.canva'
import { Route as ParticularCursosCapcutRouteImport } from './routes/particular.cursos.capcut'
import { Route as ParticularCursosChatgptRouteImport } from './routes/particular.cursos.chatgpt'
import { Route as ParticularCursosCibersegurancaRouteImport } from './routes/particular.cursos.ciberseguranca'
import { Route as ParticularCursosConteudoIaRouteImport } from './routes/particular.cursos.conteudo-ia'
import { Route as ParticularCursosCopywritingRouteImport } from './routes/particular.cursos.copywriting'
import { Route as ParticularCursosDavinciRouteImport } from './routes/particular.cursos.davinci'
import { Route as ParticularCursosEcommerceRouteImport } from './routes/particular.cursos.ecommerce'
import { Route as ParticularCursosExcelRouteImport } from './routes/particular.cursos.excel'
import { Route as ParticularCursosExcelIaRouteImport } from './routes/particular.cursos.excel-ia'
import { Route as ParticularCursosExcelPowerBiRouteImport } from './routes/particular.cursos.excel-power-bi'
import { Route as ParticularCursosFrontendRouteImport } from './routes/particular.cursos.frontend'
import { Route as ParticularCursosFullstackRouteImport } from './routes/particular.cursos.fullstack'
import { Route as ParticularCursosFunilVendasRouteImport } from './routes/particular.cursos.funil-vendas'
import { Route as ParticularCursosGitRouteImport } from './routes/particular.cursos.git'
import { Route as ParticularCursosGoogleAdsRouteImport } from './routes/particular.cursos.google-ads'
import { Route as ParticularCursosIaRouteImport } from './routes/particular.cursos.ia'
import { Route as ParticularCursosIaVisualRouteImport } from './routes/particular.cursos.ia-visual'
import { Route as ParticularCursosImpressao3dRouteImport } from './routes/particular.cursos.impressao-3d'
import { Route as ParticularCursosInformaticaRouteImport } from './routes/particular.cursos.informatica'
import { Route as ParticularCursosJogosRouteImport } from './routes/particular.cursos.jogos'
import { Route as ParticularCursosLinuxRouteImport } from './routes/particular.cursos.linux'
import { Route as ParticularCursosLogicaRouteImport } from './routes/particular.cursos.logica'
import { Route as ParticularCursosMakeRouteImport } from './routes/particular.cursos.make'
import { Route as ParticularCursosManutencaoRouteImport } from './routes/particular.cursos.manutencao'
import { Route as ParticularCursosMarketingRouteImport } from './routes/particular.cursos.marketing'
import { Route as ParticularCursosMetaAdsRouteImport } from './routes/particular.cursos.meta-ads'
import { Route as ParticularCursosMobileRouteImport } from './routes/particular.cursos.mobile'
import { Route as ParticularCursosModelagem3dRouteImport } from './routes/particular.cursos.modelagem-3d'
import { Route as ParticularCursosN8nRouteImport } from './routes/particular.cursos.n8n'
import { Route as ParticularCursosOfficeRouteImport } from './routes/particular.cursos.office'
import { Route as ParticularCursosPhotoshopRouteImport } from './routes/particular.cursos.photoshop'
import { Route as ParticularCursosPowerAppsRouteImport } from './routes/particular.cursos.power-apps'
import { Route as ParticularCursosPowerBiRouteImport } from './routes/particular.cursos.power-bi'
import { Route as ParticularCursosPowerpointRouteImport } from './routes/particular.cursos.powerpoint'
import { Route as ParticularCursosPremiereRouteImport } from './routes/particular.cursos.premiere'
import { Route as ParticularCursosPythonRouteImport } from './routes/particular.cursos.python'
import { Route as ParticularCursosPythonApisRouteImport } from './routes/particular.cursos.python-apis'
import { Route as ParticularCursosRagRouteImport } from './routes/particular.cursos.rag'
import { Route as ParticularCursosRedesRouteImport } from './routes/particular.cursos.redes'
import { Route as ParticularCursosRedesSociaisRouteImport } from './routes/particular.cursos.redes-sociais'
import { Route as ParticularCursosRevitRouteImport } from './routes/particular.cursos.revit'
import { Route as ParticularCursosSeoRouteImport } from './routes/particular.cursos.seo'
import { Route as ParticularCursosSqlRouteImport } from './routes/particular.cursos.sql'
import { Route as ParticularCursosSuporteRouteImport } from './routes/particular.cursos.suporte'
import { Route as ParticularCursosTiktokAdsRouteImport } from './routes/particular.cursos.tiktok-ads'
import { Route as ParticularCursosTypescriptRouteImport } from './routes/particular.cursos.typescript'
import { Route as ParticularCursosWordRouteImport } from './routes/particular.cursos.word'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticularRoute = ParticularRouteImport.update({
  id: '/particular',
  path: '/particular',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacoesIndexRoute = ApresentacoesIndexRouteImport.update({
  id: '/apresentacoes/',
  path: '/apresentacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacoesInformaticaCreateRoute =
  ApresentacoesInformaticaCreateRouteImport.update({
    id: '/apresentacoes/informatica-create',
    path: '/apresentacoes/informatica-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApresentacoesInformaticaJuniorRoute =
  ApresentacoesInformaticaJuniorRouteImport.update({
    id: '/apresentacoes/informatica-junior',
    path: '/apresentacoes/informatica-junior',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApresentacoesTecnologiaCreateRoute =
  ApresentacoesTecnologiaCreateRouteImport.update({
    id: '/apresentacoes/tecnologia-create',
    path: '/apresentacoes/tecnologia-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApresentacoesTecnologiaJuniorRoute =
  ApresentacoesTecnologiaJuniorRouteImport.update({
    id: '/apresentacoes/tecnologia-junior',
    path: '/apresentacoes/tecnologia-junior',
    getParentRoute: () => rootRouteImport,
  } as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CursosRoute,
} as any)
const CursosAcademiesRoute = CursosAcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => CursosRoute,
} as any)
const CursosCampsRoute = CursosCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => CursosRoute,
} as any)
const CursosCreateRoute = CursosCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CursosRoute,
} as any)
const CursosJuniorRoute = CursosJuniorRouteImport.update({
  id: '/junior',
  path: '/junior',
  getParentRoute: () => CursosRoute,
} as any)
const ParticularIndexRoute = ParticularIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticularRoute,
} as any)
const ProfessoresInformaticaCreateRoute =
  ProfessoresInformaticaCreateRouteImport.update({
    id: '/professores/informatica-create',
    path: '/professores/informatica-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessoresInformaticaJuniorRoute =
  ProfessoresInformaticaJuniorRouteImport.update({
    id: '/professores/informatica-junior',
    path: '/professores/informatica-junior',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessoresTecnologiaCreateRoute =
  ProfessoresTecnologiaCreateRouteImport.update({
    id: '/professores/tecnologia-create',
    path: '/professores/tecnologia-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessoresTecnologiaJuniorRoute =
  ProfessoresTecnologiaJuniorRouteImport.update({
    id: '/professores/tecnologia-junior',
    path: '/professores/tecnologia-junior',
    getParentRoute: () => rootRouteImport,
  } as any)
const SobreIndexRoute = SobreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SobreRoute,
} as any)
const SobreVisaoRoute = SobreVisaoRouteImport.update({
  id: '/visao',
  path: '/visao',
  getParentRoute: () => SobreRoute,
} as any)
const CursosCreateIndexRoute = CursosCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CursosCreateRoute,
} as any)
const CursosCreate1011AnosRoute = CursosCreate1011AnosRouteImport.update({
  id: '/10-11-anos',
  path: '/10-11-anos',
  getParentRoute: () => CursosCreateRoute,
} as any)
const CursosCreate1112AnosRoute = CursosCreate1112AnosRouteImport.update({
  id: '/11-12-anos',
  path: '/11-12-anos',
  getParentRoute: () => CursosCreateRoute,
} as any)
const CursosCreate1213AnosRoute = CursosCreate1213AnosRouteImport.update({
  id: '/12-13-anos',
  path: '/12-13-anos',
  getParentRoute: () => CursosCreateRoute,
} as any)
const CursosCreate1314AnosRoute = CursosCreate1314AnosRouteImport.update({
  id: '/13-14-anos',
  path: '/13-14-anos',
  getParentRoute: () => CursosCreateRoute,
} as any)
const CursosCreate89AnosRoute = CursosCreate89AnosRouteImport.update({
  id: '/8-9-anos',
  path: '/8-9-anos',
  getParentRoute: () => CursosCreateRoute,
} as any)
const CursosCreate910AnosRoute = CursosCreate910AnosRouteImport.update({
  id: '/9-10-anos',
  path: '/9-10-anos',
  getParentRoute: () => CursosCreateRoute,
} as any)
const CursosJuniorIndexRoute = CursosJuniorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CursosJuniorRoute,
} as any)
const CursosJunior56AnosRoute = CursosJunior56AnosRouteImport.update({
  id: '/5-6-anos',
  path: '/5-6-anos',
  getParentRoute: () => CursosJuniorRoute,
} as any)
const CursosJunior67AnosRoute = CursosJunior67AnosRouteImport.update({
  id: '/6-7-anos',
  path: '/6-7-anos',
  getParentRoute: () => CursosJuniorRoute,
} as any)
const CursosJunior78AnosRoute = CursosJunior78AnosRouteImport.update({
  id: '/7-8-anos',
  path: '/7-8-anos',
  getParentRoute: () => CursosJuniorRoute,
} as any)
const ParticularCursosAdsRoute = ParticularCursosAdsRouteImport.update({
  id: '/cursos/ads',
  path: '/cursos/ads',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosAgentesIaRoute =
  ParticularCursosAgentesIaRouteImport.update({
    id: '/cursos/agentes-ia',
    path: '/cursos/agentes-ia',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosAutocadRoute = ParticularCursosAutocadRouteImport.update({
  id: '/cursos/autocad',
  path: '/cursos/autocad',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosBackendRoute = ParticularCursosBackendRouteImport.update({
  id: '/cursos/backend',
  path: '/cursos/backend',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosCanvaRoute = ParticularCursosCanvaRouteImport.update({
  id: '/cursos/canva',
  path: '/cursos/canva',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosCapcutRoute = ParticularCursosCapcutRouteImport.update({
  id: '/cursos/capcut',
  path: '/cursos/capcut',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosChatgptRoute = ParticularCursosChatgptRouteImport.update({
  id: '/cursos/chatgpt',
  path: '/cursos/chatgpt',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosCibersegurancaRoute =
  ParticularCursosCibersegurancaRouteImport.update({
    id: '/cursos/ciberseguranca',
    path: '/cursos/ciberseguranca',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosConteudoIaRoute =
  ParticularCursosConteudoIaRouteImport.update({
    id: '/cursos/conteudo-ia',
    path: '/cursos/conteudo-ia',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosCopywritingRoute =
  ParticularCursosCopywritingRouteImport.update({
    id: '/cursos/copywriting',
    path: '/cursos/copywriting',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosDavinciRoute = ParticularCursosDavinciRouteImport.update({
  id: '/cursos/davinci',
  path: '/cursos/davinci',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosEcommerceRoute =
  ParticularCursosEcommerceRouteImport.update({
    id: '/cursos/ecommerce',
    path: '/cursos/ecommerce',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosExcelRoute = ParticularCursosExcelRouteImport.update({
  id: '/cursos/excel',
  path: '/cursos/excel',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosExcelIaRoute = ParticularCursosExcelIaRouteImport.update({
  id: '/cursos/excel-ia',
  path: '/cursos/excel-ia',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosExcelPowerBiRoute =
  ParticularCursosExcelPowerBiRouteImport.update({
    id: '/cursos/excel-power-bi',
    path: '/cursos/excel-power-bi',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosFrontendRoute =
  ParticularCursosFrontendRouteImport.update({
    id: '/cursos/frontend',
    path: '/cursos/frontend',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosFullstackRoute =
  ParticularCursosFullstackRouteImport.update({
    id: '/cursos/fullstack',
    path: '/cursos/fullstack',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosFunilVendasRoute =
  ParticularCursosFunilVendasRouteImport.update({
    id: '/cursos/funil-vendas',
    path: '/cursos/funil-vendas',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosGitRoute = ParticularCursosGitRouteImport.update({
  id: '/cursos/git',
  path: '/cursos/git',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosGoogleAdsRoute =
  ParticularCursosGoogleAdsRouteImport.update({
    id: '/cursos/google-ads',
    path: '/cursos/google-ads',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosIaRoute = ParticularCursosIaRouteImport.update({
  id: '/cursos/ia',
  path: '/cursos/ia',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosIaVisualRoute =
  ParticularCursosIaVisualRouteImport.update({
    id: '/cursos/ia-visual',
    path: '/cursos/ia-visual',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosImpressao3dRoute =
  ParticularCursosImpressao3dRouteImport.update({
    id: '/cursos/impressao-3d',
    path: '/cursos/impressao-3d',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosInformaticaRoute =
  ParticularCursosInformaticaRouteImport.update({
    id: '/cursos/informatica',
    path: '/cursos/informatica',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosJogosRoute = ParticularCursosJogosRouteImport.update({
  id: '/cursos/jogos',
  path: '/cursos/jogos',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosLinuxRoute = ParticularCursosLinuxRouteImport.update({
  id: '/cursos/linux',
  path: '/cursos/linux',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosLogicaRoute = ParticularCursosLogicaRouteImport.update({
  id: '/cursos/logica',
  path: '/cursos/logica',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosMakeRoute = ParticularCursosMakeRouteImport.update({
  id: '/cursos/make',
  path: '/cursos/make',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosManutencaoRoute =
  ParticularCursosManutencaoRouteImport.update({
    id: '/cursos/manutencao',
    path: '/cursos/manutencao',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosMarketingRoute =
  ParticularCursosMarketingRouteImport.update({
    id: '/cursos/marketing',
    path: '/cursos/marketing',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosMetaAdsRoute = ParticularCursosMetaAdsRouteImport.update({
  id: '/cursos/meta-ads',
  path: '/cursos/meta-ads',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosMobileRoute = ParticularCursosMobileRouteImport.update({
  id: '/cursos/mobile',
  path: '/cursos/mobile',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosModelagem3dRoute =
  ParticularCursosModelagem3dRouteImport.update({
    id: '/cursos/modelagem-3d',
    path: '/cursos/modelagem-3d',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosN8nRoute = ParticularCursosN8nRouteImport.update({
  id: '/cursos/n8n',
  path: '/cursos/n8n',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosOfficeRoute = ParticularCursosOfficeRouteImport.update({
  id: '/cursos/office',
  path: '/cursos/office',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosPhotoshopRoute =
  ParticularCursosPhotoshopRouteImport.update({
    id: '/cursos/photoshop',
    path: '/cursos/photoshop',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosPowerAppsRoute =
  ParticularCursosPowerAppsRouteImport.update({
    id: '/cursos/power-apps',
    path: '/cursos/power-apps',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosPowerBiRoute = ParticularCursosPowerBiRouteImport.update({
  id: '/cursos/power-bi',
  path: '/cursos/power-bi',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosPowerpointRoute =
  ParticularCursosPowerpointRouteImport.update({
    id: '/cursos/powerpoint',
    path: '/cursos/powerpoint',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosPremiereRoute =
  ParticularCursosPremiereRouteImport.update({
    id: '/cursos/premiere',
    path: '/cursos/premiere',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosPythonRoute = ParticularCursosPythonRouteImport.update({
  id: '/cursos/python',
  path: '/cursos/python',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosPythonApisRoute =
  ParticularCursosPythonApisRouteImport.update({
    id: '/cursos/python-apis',
    path: '/cursos/python-apis',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosRagRoute = ParticularCursosRagRouteImport.update({
  id: '/cursos/rag',
  path: '/cursos/rag',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosRedesRoute = ParticularCursosRedesRouteImport.update({
  id: '/cursos/redes',
  path: '/cursos/redes',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosRedesSociaisRoute =
  ParticularCursosRedesSociaisRouteImport.update({
    id: '/cursos/redes-sociais',
    path: '/cursos/redes-sociais',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosRevitRoute = ParticularCursosRevitRouteImport.update({
  id: '/cursos/revit',
  path: '/cursos/revit',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosSeoRoute = ParticularCursosSeoRouteImport.update({
  id: '/cursos/seo',
  path: '/cursos/seo',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosSqlRoute = ParticularCursosSqlRouteImport.update({
  id: '/cursos/sql',
  path: '/cursos/sql',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosSuporteRoute = ParticularCursosSuporteRouteImport.update({
  id: '/cursos/suporte',
  path: '/cursos/suporte',
  getParentRoute: () => ParticularRoute,
} as any)
const ParticularCursosTiktokAdsRoute =
  ParticularCursosTiktokAdsRouteImport.update({
    id: '/cursos/tiktok-ads',
    path: '/cursos/tiktok-ads',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosTypescriptRoute =
  ParticularCursosTypescriptRouteImport.update({
    id: '/cursos/typescript',
    path: '/cursos/typescript',
    getParentRoute: () => ParticularRoute,
  } as any)
const ParticularCursosWordRoute = ParticularCursosWordRouteImport.update({
  id: '/cursos/word',
  path: '/cursos/word',
  getParentRoute: () => ParticularRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRouteWithChildren
  '/links': typeof LinksRoute
  '/particular': typeof ParticularRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRouteWithChildren
  '/termos': typeof TermosRoute
  '/apresentacoes/informatica-create': typeof ApresentacoesInformaticaCreateRoute
  '/apresentacoes/informatica-junior': typeof ApresentacoesInformaticaJuniorRoute
  '/apresentacoes/tecnologia-create': typeof ApresentacoesTecnologiaCreateRoute
  '/apresentacoes/tecnologia-junior': typeof ApresentacoesTecnologiaJuniorRoute
  '/cursos/academies': typeof CursosAcademiesRoute
  '/cursos/camps': typeof CursosCampsRoute
  '/cursos/create': typeof CursosCreateRouteWithChildren
  '/cursos/junior': typeof CursosJuniorRouteWithChildren
  '/professores/informatica-create': typeof ProfessoresInformaticaCreateRoute
  '/professores/informatica-junior': typeof ProfessoresInformaticaJuniorRoute
  '/professores/tecnologia-create': typeof ProfessoresTecnologiaCreateRoute
  '/professores/tecnologia-junior': typeof ProfessoresTecnologiaJuniorRoute
  '/sobre/visao': typeof SobreVisaoRoute
  '/apresentacoes/': typeof ApresentacoesIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/particular/': typeof ParticularIndexRoute
  '/sobre/': typeof SobreIndexRoute
  '/cursos/create/10-11-anos': typeof CursosCreate1011AnosRoute
  '/cursos/create/11-12-anos': typeof CursosCreate1112AnosRoute
  '/cursos/create/12-13-anos': typeof CursosCreate1213AnosRoute
  '/cursos/create/13-14-anos': typeof CursosCreate1314AnosRoute
  '/cursos/create/8-9-anos': typeof CursosCreate89AnosRoute
  '/cursos/create/9-10-anos': typeof CursosCreate910AnosRoute
  '/cursos/junior/5-6-anos': typeof CursosJunior56AnosRoute
  '/cursos/junior/6-7-anos': typeof CursosJunior67AnosRoute
  '/cursos/junior/7-8-anos': typeof CursosJunior78AnosRoute
  '/particular/cursos/ads': typeof ParticularCursosAdsRoute
  '/particular/cursos/agentes-ia': typeof ParticularCursosAgentesIaRoute
  '/particular/cursos/autocad': typeof ParticularCursosAutocadRoute
  '/particular/cursos/backend': typeof ParticularCursosBackendRoute
  '/particular/cursos/canva': typeof ParticularCursosCanvaRoute
  '/particular/cursos/capcut': typeof ParticularCursosCapcutRoute
  '/particular/cursos/chatgpt': typeof ParticularCursosChatgptRoute
  '/particular/cursos/ciberseguranca': typeof ParticularCursosCibersegurancaRoute
  '/particular/cursos/conteudo-ia': typeof ParticularCursosConteudoIaRoute
  '/particular/cursos/copywriting': typeof ParticularCursosCopywritingRoute
  '/particular/cursos/davinci': typeof ParticularCursosDavinciRoute
  '/particular/cursos/ecommerce': typeof ParticularCursosEcommerceRoute
  '/particular/cursos/excel': typeof ParticularCursosExcelRoute
  '/particular/cursos/excel-ia': typeof ParticularCursosExcelIaRoute
  '/particular/cursos/excel-power-bi': typeof ParticularCursosExcelPowerBiRoute
  '/particular/cursos/frontend': typeof ParticularCursosFrontendRoute
  '/particular/cursos/fullstack': typeof ParticularCursosFullstackRoute
  '/particular/cursos/funil-vendas': typeof ParticularCursosFunilVendasRoute
  '/particular/cursos/git': typeof ParticularCursosGitRoute
  '/particular/cursos/google-ads': typeof ParticularCursosGoogleAdsRoute
  '/particular/cursos/ia': typeof ParticularCursosIaRoute
  '/particular/cursos/ia-visual': typeof ParticularCursosIaVisualRoute
  '/particular/cursos/impressao-3d': typeof ParticularCursosImpressao3dRoute
  '/particular/cursos/informatica': typeof ParticularCursosInformaticaRoute
  '/particular/cursos/jogos': typeof ParticularCursosJogosRoute
  '/particular/cursos/linux': typeof ParticularCursosLinuxRoute
  '/particular/cursos/logica': typeof ParticularCursosLogicaRoute
  '/particular/cursos/make': typeof ParticularCursosMakeRoute
  '/particular/cursos/manutencao': typeof ParticularCursosManutencaoRoute
  '/particular/cursos/marketing': typeof ParticularCursosMarketingRoute
  '/particular/cursos/meta-ads': typeof ParticularCursosMetaAdsRoute
  '/particular/cursos/mobile': typeof ParticularCursosMobileRoute
  '/particular/cursos/modelagem-3d': typeof ParticularCursosModelagem3dRoute
  '/particular/cursos/n8n': typeof ParticularCursosN8nRoute
  '/particular/cursos/office': typeof ParticularCursosOfficeRoute
  '/particular/cursos/photoshop': typeof ParticularCursosPhotoshopRoute
  '/particular/cursos/power-apps': typeof ParticularCursosPowerAppsRoute
  '/particular/cursos/power-bi': typeof ParticularCursosPowerBiRoute
  '/particular/cursos/powerpoint': typeof ParticularCursosPowerpointRoute
  '/particular/cursos/premiere': typeof ParticularCursosPremiereRoute
  '/particular/cursos/python': typeof ParticularCursosPythonRoute
  '/particular/cursos/python-apis': typeof ParticularCursosPythonApisRoute
  '/particular/cursos/rag': typeof ParticularCursosRagRoute
  '/particular/cursos/redes': typeof ParticularCursosRedesRoute
  '/particular/cursos/redes-sociais': typeof ParticularCursosRedesSociaisRoute
  '/particular/cursos/revit': typeof ParticularCursosRevitRoute
  '/particular/cursos/seo': typeof ParticularCursosSeoRoute
  '/particular/cursos/sql': typeof ParticularCursosSqlRoute
  '/particular/cursos/suporte': typeof ParticularCursosSuporteRoute
  '/particular/cursos/tiktok-ads': typeof ParticularCursosTiktokAdsRoute
  '/particular/cursos/typescript': typeof ParticularCursosTypescriptRoute
  '/particular/cursos/word': typeof ParticularCursosWordRoute
  '/cursos/create/': typeof CursosCreateIndexRoute
  '/cursos/junior/': typeof CursosJuniorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/links': typeof LinksRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/apresentacoes/informatica-create': typeof ApresentacoesInformaticaCreateRoute
  '/apresentacoes/informatica-junior': typeof ApresentacoesInformaticaJuniorRoute
  '/apresentacoes/tecnologia-create': typeof ApresentacoesTecnologiaCreateRoute
  '/apresentacoes/tecnologia-junior': typeof ApresentacoesTecnologiaJuniorRoute
  '/cursos/academies': typeof CursosAcademiesRoute
  '/cursos/camps': typeof CursosCampsRoute
  '/professores/informatica-create': typeof ProfessoresInformaticaCreateRoute
  '/professores/informatica-junior': typeof ProfessoresInformaticaJuniorRoute
  '/professores/tecnologia-create': typeof ProfessoresTecnologiaCreateRoute
  '/professores/tecnologia-junior': typeof ProfessoresTecnologiaJuniorRoute
  '/sobre/visao': typeof SobreVisaoRoute
  '/apresentacoes': typeof ApresentacoesIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/particular': typeof ParticularIndexRoute
  '/sobre': typeof SobreIndexRoute
  '/cursos/create/10-11-anos': typeof CursosCreate1011AnosRoute
  '/cursos/create/11-12-anos': typeof CursosCreate1112AnosRoute
  '/cursos/create/12-13-anos': typeof CursosCreate1213AnosRoute
  '/cursos/create/13-14-anos': typeof CursosCreate1314AnosRoute
  '/cursos/create/8-9-anos': typeof CursosCreate89AnosRoute
  '/cursos/create/9-10-anos': typeof CursosCreate910AnosRoute
  '/cursos/junior/5-6-anos': typeof CursosJunior56AnosRoute
  '/cursos/junior/6-7-anos': typeof CursosJunior67AnosRoute
  '/cursos/junior/7-8-anos': typeof CursosJunior78AnosRoute
  '/particular/cursos/ads': typeof ParticularCursosAdsRoute
  '/particular/cursos/agentes-ia': typeof ParticularCursosAgentesIaRoute
  '/particular/cursos/autocad': typeof ParticularCursosAutocadRoute
  '/particular/cursos/backend': typeof ParticularCursosBackendRoute
  '/particular/cursos/canva': typeof ParticularCursosCanvaRoute
  '/particular/cursos/capcut': typeof ParticularCursosCapcutRoute
  '/particular/cursos/chatgpt': typeof ParticularCursosChatgptRoute
  '/particular/cursos/ciberseguranca': typeof ParticularCursosCibersegurancaRoute
  '/particular/cursos/conteudo-ia': typeof ParticularCursosConteudoIaRoute
  '/particular/cursos/copywriting': typeof ParticularCursosCopywritingRoute
  '/particular/cursos/davinci': typeof ParticularCursosDavinciRoute
  '/particular/cursos/ecommerce': typeof ParticularCursosEcommerceRoute
  '/particular/cursos/excel': typeof ParticularCursosExcelRoute
  '/particular/cursos/excel-ia': typeof ParticularCursosExcelIaRoute
  '/particular/cursos/excel-power-bi': typeof ParticularCursosExcelPowerBiRoute
  '/particular/cursos/frontend': typeof ParticularCursosFrontendRoute
  '/particular/cursos/fullstack': typeof ParticularCursosFullstackRoute
  '/particular/cursos/funil-vendas': typeof ParticularCursosFunilVendasRoute
  '/particular/cursos/git': typeof ParticularCursosGitRoute
  '/particular/cursos/google-ads': typeof ParticularCursosGoogleAdsRoute
  '/particular/cursos/ia': typeof ParticularCursosIaRoute
  '/particular/cursos/ia-visual': typeof ParticularCursosIaVisualRoute
  '/particular/cursos/impressao-3d': typeof ParticularCursosImpressao3dRoute
  '/particular/cursos/informatica': typeof ParticularCursosInformaticaRoute
  '/particular/cursos/jogos': typeof ParticularCursosJogosRoute
  '/particular/cursos/linux': typeof ParticularCursosLinuxRoute
  '/particular/cursos/logica': typeof ParticularCursosLogicaRoute
  '/particular/cursos/make': typeof ParticularCursosMakeRoute
  '/particular/cursos/manutencao': typeof ParticularCursosManutencaoRoute
  '/particular/cursos/marketing': typeof ParticularCursosMarketingRoute
  '/particular/cursos/meta-ads': typeof ParticularCursosMetaAdsRoute
  '/particular/cursos/mobile': typeof ParticularCursosMobileRoute
  '/particular/cursos/modelagem-3d': typeof ParticularCursosModelagem3dRoute
  '/particular/cursos/n8n': typeof ParticularCursosN8nRoute
  '/particular/cursos/office': typeof ParticularCursosOfficeRoute
  '/particular/cursos/photoshop': typeof ParticularCursosPhotoshopRoute
  '/particular/cursos/power-apps': typeof ParticularCursosPowerAppsRoute
  '/particular/cursos/power-bi': typeof ParticularCursosPowerBiRoute
  '/particular/cursos/powerpoint': typeof ParticularCursosPowerpointRoute
  '/particular/cursos/premiere': typeof ParticularCursosPremiereRoute
  '/particular/cursos/python': typeof ParticularCursosPythonRoute
  '/particular/cursos/python-apis': typeof ParticularCursosPythonApisRoute
  '/particular/cursos/rag': typeof ParticularCursosRagRoute
  '/particular/cursos/redes': typeof ParticularCursosRedesRoute
  '/particular/cursos/redes-sociais': typeof ParticularCursosRedesSociaisRoute
  '/particular/cursos/revit': typeof ParticularCursosRevitRoute
  '/particular/cursos/seo': typeof ParticularCursosSeoRoute
  '/particular/cursos/sql': typeof ParticularCursosSqlRoute
  '/particular/cursos/suporte': typeof ParticularCursosSuporteRoute
  '/particular/cursos/tiktok-ads': typeof ParticularCursosTiktokAdsRoute
  '/particular/cursos/typescript': typeof ParticularCursosTypescriptRoute
  '/particular/cursos/word': typeof ParticularCursosWordRoute
  '/cursos/create': typeof CursosCreateIndexRoute
  '/cursos/junior': typeof CursosJuniorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRouteWithChildren
  '/links': typeof LinksRoute
  '/particular': typeof ParticularRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRouteWithChildren
  '/termos': typeof TermosRoute
  '/apresentacoes/informatica-create': typeof ApresentacoesInformaticaCreateRoute
  '/apresentacoes/informatica-junior': typeof ApresentacoesInformaticaJuniorRoute
  '/apresentacoes/tecnologia-create': typeof ApresentacoesTecnologiaCreateRoute
  '/apresentacoes/tecnologia-junior': typeof ApresentacoesTecnologiaJuniorRoute
  '/cursos/academies': typeof CursosAcademiesRoute
  '/cursos/camps': typeof CursosCampsRoute
  '/cursos/create': typeof CursosCreateRouteWithChildren
  '/cursos/junior': typeof CursosJuniorRouteWithChildren
  '/professores/informatica-create': typeof ProfessoresInformaticaCreateRoute
  '/professores/informatica-junior': typeof ProfessoresInformaticaJuniorRoute
  '/professores/tecnologia-create': typeof ProfessoresTecnologiaCreateRoute
  '/professores/tecnologia-junior': typeof ProfessoresTecnologiaJuniorRoute
  '/sobre/visao': typeof SobreVisaoRoute
  '/apresentacoes/': typeof ApresentacoesIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/particular/': typeof ParticularIndexRoute
  '/sobre/': typeof SobreIndexRoute
  '/cursos/create/10-11-anos': typeof CursosCreate1011AnosRoute
  '/cursos/create/11-12-anos': typeof CursosCreate1112AnosRoute
  '/cursos/create/12-13-anos': typeof CursosCreate1213AnosRoute
  '/cursos/create/13-14-anos': typeof CursosCreate1314AnosRoute
  '/cursos/create/8-9-anos': typeof CursosCreate89AnosRoute
  '/cursos/create/9-10-anos': typeof CursosCreate910AnosRoute
  '/cursos/junior/5-6-anos': typeof CursosJunior56AnosRoute
  '/cursos/junior/6-7-anos': typeof CursosJunior67AnosRoute
  '/cursos/junior/7-8-anos': typeof CursosJunior78AnosRoute
  '/particular/cursos/ads': typeof ParticularCursosAdsRoute
  '/particular/cursos/agentes-ia': typeof ParticularCursosAgentesIaRoute
  '/particular/cursos/autocad': typeof ParticularCursosAutocadRoute
  '/particular/cursos/backend': typeof ParticularCursosBackendRoute
  '/particular/cursos/canva': typeof ParticularCursosCanvaRoute
  '/particular/cursos/capcut': typeof ParticularCursosCapcutRoute
  '/particular/cursos/chatgpt': typeof ParticularCursosChatgptRoute
  '/particular/cursos/ciberseguranca': typeof ParticularCursosCibersegurancaRoute
  '/particular/cursos/conteudo-ia': typeof ParticularCursosConteudoIaRoute
  '/particular/cursos/copywriting': typeof ParticularCursosCopywritingRoute
  '/particular/cursos/davinci': typeof ParticularCursosDavinciRoute
  '/particular/cursos/ecommerce': typeof ParticularCursosEcommerceRoute
  '/particular/cursos/excel': typeof ParticularCursosExcelRoute
  '/particular/cursos/excel-ia': typeof ParticularCursosExcelIaRoute
  '/particular/cursos/excel-power-bi': typeof ParticularCursosExcelPowerBiRoute
  '/particular/cursos/frontend': typeof ParticularCursosFrontendRoute
  '/particular/cursos/fullstack': typeof ParticularCursosFullstackRoute
  '/particular/cursos/funil-vendas': typeof ParticularCursosFunilVendasRoute
  '/particular/cursos/git': typeof ParticularCursosGitRoute
  '/particular/cursos/google-ads': typeof ParticularCursosGoogleAdsRoute
  '/particular/cursos/ia': typeof ParticularCursosIaRoute
  '/particular/cursos/ia-visual': typeof ParticularCursosIaVisualRoute
  '/particular/cursos/impressao-3d': typeof ParticularCursosImpressao3dRoute
  '/particular/cursos/informatica': typeof ParticularCursosInformaticaRoute
  '/particular/cursos/jogos': typeof ParticularCursosJogosRoute
  '/particular/cursos/linux': typeof ParticularCursosLinuxRoute
  '/particular/cursos/logica': typeof ParticularCursosLogicaRoute
  '/particular/cursos/make': typeof ParticularCursosMakeRoute
  '/particular/cursos/manutencao': typeof ParticularCursosManutencaoRoute
  '/particular/cursos/marketing': typeof ParticularCursosMarketingRoute
  '/particular/cursos/meta-ads': typeof ParticularCursosMetaAdsRoute
  '/particular/cursos/mobile': typeof ParticularCursosMobileRoute
  '/particular/cursos/modelagem-3d': typeof ParticularCursosModelagem3dRoute
  '/particular/cursos/n8n': typeof ParticularCursosN8nRoute
  '/particular/cursos/office': typeof ParticularCursosOfficeRoute
  '/particular/cursos/photoshop': typeof ParticularCursosPhotoshopRoute
  '/particular/cursos/power-apps': typeof ParticularCursosPowerAppsRoute
  '/particular/cursos/power-bi': typeof ParticularCursosPowerBiRoute
  '/particular/cursos/powerpoint': typeof ParticularCursosPowerpointRoute
  '/particular/cursos/premiere': typeof ParticularCursosPremiereRoute
  '/particular/cursos/python': typeof ParticularCursosPythonRoute
  '/particular/cursos/python-apis': typeof ParticularCursosPythonApisRoute
  '/particular/cursos/rag': typeof ParticularCursosRagRoute
  '/particular/cursos/redes': typeof ParticularCursosRedesRoute
  '/particular/cursos/redes-sociais': typeof ParticularCursosRedesSociaisRoute
  '/particular/cursos/revit': typeof ParticularCursosRevitRoute
  '/particular/cursos/seo': typeof ParticularCursosSeoRoute
  '/particular/cursos/sql': typeof ParticularCursosSqlRoute
  '/particular/cursos/suporte': typeof ParticularCursosSuporteRoute
  '/particular/cursos/tiktok-ads': typeof ParticularCursosTiktokAdsRoute
  '/particular/cursos/typescript': typeof ParticularCursosTypescriptRoute
  '/particular/cursos/word': typeof ParticularCursosWordRoute
  '/cursos/create/': typeof CursosCreateIndexRoute
  '/cursos/junior/': typeof CursosJuniorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/cursos'
    | '/links'
    | '/particular'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/apresentacoes/informatica-create'
    | '/apresentacoes/informatica-junior'
    | '/apresentacoes/tecnologia-create'
    | '/apresentacoes/tecnologia-junior'
    | '/cursos/academies'
    | '/cursos/camps'
    | '/cursos/create'
    | '/cursos/junior'
    | '/professores/informatica-create'
    | '/professores/informatica-junior'
    | '/professores/tecnologia-create'
    | '/professores/tecnologia-junior'
    | '/sobre/visao'
    | '/apresentacoes/'
    | '/cursos/'
    | '/particular/'
    | '/sobre/'
    | '/cursos/create/10-11-anos'
    | '/cursos/create/11-12-anos'
    | '/cursos/create/12-13-anos'
    | '/cursos/create/13-14-anos'
    | '/cursos/create/8-9-anos'
    | '/cursos/create/9-10-anos'
    | '/cursos/junior/5-6-anos'
    | '/cursos/junior/6-7-anos'
    | '/cursos/junior/7-8-anos'
    | '/particular/cursos/ads'
    | '/particular/cursos/agentes-ia'
    | '/particular/cursos/autocad'
    | '/particular/cursos/backend'
    | '/particular/cursos/canva'
    | '/particular/cursos/capcut'
    | '/particular/cursos/chatgpt'
    | '/particular/cursos/ciberseguranca'
    | '/particular/cursos/conteudo-ia'
    | '/particular/cursos/copywriting'
    | '/particular/cursos/davinci'
    | '/particular/cursos/ecommerce'
    | '/particular/cursos/excel'
    | '/particular/cursos/excel-ia'
    | '/particular/cursos/excel-power-bi'
    | '/particular/cursos/frontend'
    | '/particular/cursos/fullstack'
    | '/particular/cursos/funil-vendas'
    | '/particular/cursos/git'
    | '/particular/cursos/google-ads'
    | '/particular/cursos/ia'
    | '/particular/cursos/ia-visual'
    | '/particular/cursos/impressao-3d'
    | '/particular/cursos/informatica'
    | '/particular/cursos/jogos'
    | '/particular/cursos/linux'
    | '/particular/cursos/logica'
    | '/particular/cursos/make'
    | '/particular/cursos/manutencao'
    | '/particular/cursos/marketing'
    | '/particular/cursos/meta-ads'
    | '/particular/cursos/mobile'
    | '/particular/cursos/modelagem-3d'
    | '/particular/cursos/n8n'
    | '/particular/cursos/office'
    | '/particular/cursos/photoshop'
    | '/particular/cursos/power-apps'
    | '/particular/cursos/power-bi'
    | '/particular/cursos/powerpoint'
    | '/particular/cursos/premiere'
    | '/particular/cursos/python'
    | '/particular/cursos/python-apis'
    | '/particular/cursos/rag'
    | '/particular/cursos/redes'
    | '/particular/cursos/redes-sociais'
    | '/particular/cursos/revit'
    | '/particular/cursos/seo'
    | '/particular/cursos/sql'
    | '/particular/cursos/suporte'
    | '/particular/cursos/tiktok-ads'
    | '/particular/cursos/typescript'
    | '/particular/cursos/word'
    | '/cursos/create/'
    | '/cursos/junior/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/links'
    | '/privacidade'
    | '/termos'
    | '/apresentacoes/informatica-create'
    | '/apresentacoes/informatica-junior'
    | '/apresentacoes/tecnologia-create'
    | '/apresentacoes/tecnologia-junior'
    | '/cursos/academies'
    | '/cursos/camps'
    | '/professores/informatica-create'
    | '/professores/informatica-junior'
    | '/professores/tecnologia-create'
    | '/professores/tecnologia-junior'
    | '/sobre/visao'
    | '/apresentacoes'
    | '/cursos'
    | '/particular'
    | '/sobre'
    | '/cursos/create/10-11-anos'
    | '/cursos/create/11-12-anos'
    | '/cursos/create/12-13-anos'
    | '/cursos/create/13-14-anos'
    | '/cursos/create/8-9-anos'
    | '/cursos/create/9-10-anos'
    | '/cursos/junior/5-6-anos'
    | '/cursos/junior/6-7-anos'
    | '/cursos/junior/7-8-anos'
    | '/particular/cursos/ads'
    | '/particular/cursos/agentes-ia'
    | '/particular/cursos/autocad'
    | '/particular/cursos/backend'
    | '/particular/cursos/canva'
    | '/particular/cursos/capcut'
    | '/particular/cursos/chatgpt'
    | '/particular/cursos/ciberseguranca'
    | '/particular/cursos/conteudo-ia'
    | '/particular/cursos/copywriting'
    | '/particular/cursos/davinci'
    | '/particular/cursos/ecommerce'
    | '/particular/cursos/excel'
    | '/particular/cursos/excel-ia'
    | '/particular/cursos/excel-power-bi'
    | '/particular/cursos/frontend'
    | '/particular/cursos/fullstack'
    | '/particular/cursos/funil-vendas'
    | '/particular/cursos/git'
    | '/particular/cursos/google-ads'
    | '/particular/cursos/ia'
    | '/particular/cursos/ia-visual'
    | '/particular/cursos/impressao-3d'
    | '/particular/cursos/informatica'
    | '/particular/cursos/jogos'
    | '/particular/cursos/linux'
    | '/particular/cursos/logica'
    | '/particular/cursos/make'
    | '/particular/cursos/manutencao'
    | '/particular/cursos/marketing'
    | '/particular/cursos/meta-ads'
    | '/particular/cursos/mobile'
    | '/particular/cursos/modelagem-3d'
    | '/particular/cursos/n8n'
    | '/particular/cursos/office'
    | '/particular/cursos/photoshop'
    | '/particular/cursos/power-apps'
    | '/particular/cursos/power-bi'
    | '/particular/cursos/powerpoint'
    | '/particular/cursos/premiere'
    | '/particular/cursos/python'
    | '/particular/cursos/python-apis'
    | '/particular/cursos/rag'
    | '/particular/cursos/redes'
    | '/particular/cursos/redes-sociais'
    | '/particular/cursos/revit'
    | '/particular/cursos/seo'
    | '/particular/cursos/sql'
    | '/particular/cursos/suporte'
    | '/particular/cursos/tiktok-ads'
    | '/particular/cursos/typescript'
    | '/particular/cursos/word'
    | '/cursos/create'
    | '/cursos/junior'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/cursos'
    | '/links'
    | '/particular'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/apresentacoes/informatica-create'
    | '/apresentacoes/informatica-junior'
    | '/apresentacoes/tecnologia-create'
    | '/apresentacoes/tecnologia-junior'
    | '/cursos/academies'
    | '/cursos/camps'
    | '/cursos/create'
    | '/cursos/junior'
    | '/professores/informatica-create'
    | '/professores/informatica-junior'
    | '/professores/tecnologia-create'
    | '/professores/tecnologia-junior'
    | '/sobre/visao'
    | '/apresentacoes/'
    | '/cursos/'
    | '/particular/'
    | '/sobre/'
    | '/cursos/create/10-11-anos'
    | '/cursos/create/11-12-anos'
    | '/cursos/create/12-13-anos'
    | '/cursos/create/13-14-anos'
    | '/cursos/create/8-9-anos'
    | '/cursos/create/9-10-anos'
    | '/cursos/junior/5-6-anos'
    | '/cursos/junior/6-7-anos'
    | '/cursos/junior/7-8-anos'
    | '/particular/cursos/ads'
    | '/particular/cursos/agentes-ia'
    | '/particular/cursos/autocad'
    | '/particular/cursos/backend'
    | '/particular/cursos/canva'
    | '/particular/cursos/capcut'
    | '/particular/cursos/chatgpt'
    | '/particular/cursos/ciberseguranca'
    | '/particular/cursos/conteudo-ia'
    | '/particular/cursos/copywriting'
    | '/particular/cursos/davinci'
    | '/particular/cursos/ecommerce'
    | '/particular/cursos/excel'
    | '/particular/cursos/excel-ia'
    | '/particular/cursos/excel-power-bi'
    | '/particular/cursos/frontend'
    | '/particular/cursos/fullstack'
    | '/particular/cursos/funil-vendas'
    | '/particular/cursos/git'
    | '/particular/cursos/google-ads'
    | '/particular/cursos/ia'
    | '/particular/cursos/ia-visual'
    | '/particular/cursos/impressao-3d'
    | '/particular/cursos/informatica'
    | '/particular/cursos/jogos'
    | '/particular/cursos/linux'
    | '/particular/cursos/logica'
    | '/particular/cursos/make'
    | '/particular/cursos/manutencao'
    | '/particular/cursos/marketing'
    | '/particular/cursos/meta-ads'
    | '/particular/cursos/mobile'
    | '/particular/cursos/modelagem-3d'
    | '/particular/cursos/n8n'
    | '/particular/cursos/office'
    | '/particular/cursos/photoshop'
    | '/particular/cursos/power-apps'
    | '/particular/cursos/power-bi'
    | '/particular/cursos/powerpoint'
    | '/particular/cursos/premiere'
    | '/particular/cursos/python'
    | '/particular/cursos/python-apis'
    | '/particular/cursos/rag'
    | '/particular/cursos/redes'
    | '/particular/cursos/redes-sociais'
    | '/particular/cursos/revit'
    | '/particular/cursos/seo'
    | '/particular/cursos/sql'
    | '/particular/cursos/suporte'
    | '/particular/cursos/tiktok-ads'
    | '/particular/cursos/typescript'
    | '/particular/cursos/word'
    | '/cursos/create/'
    | '/cursos/junior/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRouteWithChildren
  LinksRoute: typeof LinksRoute
  ParticularRoute: typeof ParticularRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRouteWithChildren
  TermosRoute: typeof TermosRoute
  ApresentacoesInformaticaCreateRoute: typeof ApresentacoesInformaticaCreateRoute
  ApresentacoesInformaticaJuniorRoute: typeof ApresentacoesInformaticaJuniorRoute
  ApresentacoesTecnologiaCreateRoute: typeof ApresentacoesTecnologiaCreateRoute
  ApresentacoesTecnologiaJuniorRoute: typeof ApresentacoesTecnologiaJuniorRoute
  ProfessoresInformaticaCreateRoute: typeof ProfessoresInformaticaCreateRoute
  ProfessoresInformaticaJuniorRoute: typeof ProfessoresInformaticaJuniorRoute
  ProfessoresTecnologiaCreateRoute: typeof ProfessoresTecnologiaCreateRoute
  ProfessoresTecnologiaJuniorRoute: typeof ProfessoresTecnologiaJuniorRoute
  ApresentacoesIndexRoute: typeof ApresentacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/particular': {
      id: '/particular'
      path: '/particular'
      fullPath: '/particular'
      preLoaderRoute: typeof ParticularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacoes/': {
      id: '/apresentacoes/'
      path: '/apresentacoes'
      fullPath: '/apresentacoes/'
      preLoaderRoute: typeof ApresentacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacoes/informatica-create': {
      id: '/apresentacoes/informatica-create'
      path: '/apresentacoes/informatica-create'
      fullPath: '/apresentacoes/informatica-create'
      preLoaderRoute: typeof ApresentacoesInformaticaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacoes/informatica-junior': {
      id: '/apresentacoes/informatica-junior'
      path: '/apresentacoes/informatica-junior'
      fullPath: '/apresentacoes/informatica-junior'
      preLoaderRoute: typeof ApresentacoesInformaticaJuniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacoes/tecnologia-create': {
      id: '/apresentacoes/tecnologia-create'
      path: '/apresentacoes/tecnologia-create'
      fullPath: '/apresentacoes/tecnologia-create'
      preLoaderRoute: typeof ApresentacoesTecnologiaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacoes/tecnologia-junior': {
      id: '/apresentacoes/tecnologia-junior'
      path: '/apresentacoes/tecnologia-junior'
      fullPath: '/apresentacoes/tecnologia-junior'
      preLoaderRoute: typeof ApresentacoesTecnologiaJuniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof CursosRoute
    }
    '/cursos/academies': {
      id: '/cursos/academies'
      path: '/academies'
      fullPath: '/cursos/academies'
      preLoaderRoute: typeof CursosAcademiesRouteImport
      parentRoute: typeof CursosRoute
    }
    '/cursos/camps': {
      id: '/cursos/camps'
      path: '/camps'
      fullPath: '/cursos/camps'
      preLoaderRoute: typeof CursosCampsRouteImport
      parentRoute: typeof CursosRoute
    }
    '/cursos/create': {
      id: '/cursos/create'
      path: '/create'
      fullPath: '/cursos/create'
      preLoaderRoute: typeof CursosCreateRouteImport
      parentRoute: typeof CursosRoute
    }
    '/cursos/junior': {
      id: '/cursos/junior'
      path: '/junior'
      fullPath: '/cursos/junior'
      preLoaderRoute: typeof CursosJuniorRouteImport
      parentRoute: typeof CursosRoute
    }
    '/particular/': {
      id: '/particular/'
      path: '/'
      fullPath: '/particular/'
      preLoaderRoute: typeof ParticularIndexRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/professores/informatica-create': {
      id: '/professores/informatica-create'
      path: '/professores/informatica-create'
      fullPath: '/professores/informatica-create'
      preLoaderRoute: typeof ProfessoresInformaticaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores/informatica-junior': {
      id: '/professores/informatica-junior'
      path: '/professores/informatica-junior'
      fullPath: '/professores/informatica-junior'
      preLoaderRoute: typeof ProfessoresInformaticaJuniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores/tecnologia-create': {
      id: '/professores/tecnologia-create'
      path: '/professores/tecnologia-create'
      fullPath: '/professores/tecnologia-create'
      preLoaderRoute: typeof ProfessoresTecnologiaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores/tecnologia-junior': {
      id: '/professores/tecnologia-junior'
      path: '/professores/tecnologia-junior'
      fullPath: '/professores/tecnologia-junior'
      preLoaderRoute: typeof ProfessoresTecnologiaJuniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/': {
      id: '/sobre/'
      path: '/'
      fullPath: '/sobre/'
      preLoaderRoute: typeof SobreIndexRouteImport
      parentRoute: typeof SobreRoute
    }
    '/sobre/visao': {
      id: '/sobre/visao'
      path: '/visao'
      fullPath: '/sobre/visao'
      preLoaderRoute: typeof SobreVisaoRouteImport
      parentRoute: typeof SobreRoute
    }
    '/cursos/create/': {
      id: '/cursos/create/'
      path: '/'
      fullPath: '/cursos/create/'
      preLoaderRoute: typeof CursosCreateIndexRouteImport
      parentRoute: typeof CursosCreateRoute
    }
    '/cursos/create/10-11-anos': {
      id: '/cursos/create/10-11-anos'
      path: '/10-11-anos'
      fullPath: '/cursos/create/10-11-anos'
      preLoaderRoute: typeof CursosCreate1011AnosRouteImport
      parentRoute: typeof CursosCreateRoute
    }
    '/cursos/create/11-12-anos': {
      id: '/cursos/create/11-12-anos'
      path: '/11-12-anos'
      fullPath: '/cursos/create/11-12-anos'
      preLoaderRoute: typeof CursosCreate1112AnosRouteImport
      parentRoute: typeof CursosCreateRoute
    }
    '/cursos/create/12-13-anos': {
      id: '/cursos/create/12-13-anos'
      path: '/12-13-anos'
      fullPath: '/cursos/create/12-13-anos'
      preLoaderRoute: typeof CursosCreate1213AnosRouteImport
      parentRoute: typeof CursosCreateRoute
    }
    '/cursos/create/13-14-anos': {
      id: '/cursos/create/13-14-anos'
      path: '/13-14-anos'
      fullPath: '/cursos/create/13-14-anos'
      preLoaderRoute: typeof CursosCreate1314AnosRouteImport
      parentRoute: typeof CursosCreateRoute
    }
    '/cursos/create/8-9-anos': {
      id: '/cursos/create/8-9-anos'
      path: '/8-9-anos'
      fullPath: '/cursos/create/8-9-anos'
      preLoaderRoute: typeof CursosCreate89AnosRouteImport
      parentRoute: typeof CursosCreateRoute
    }
    '/cursos/create/9-10-anos': {
      id: '/cursos/create/9-10-anos'
      path: '/9-10-anos'
      fullPath: '/cursos/create/9-10-anos'
      preLoaderRoute: typeof CursosCreate910AnosRouteImport
      parentRoute: typeof CursosCreateRoute
    }
    '/cursos/junior/': {
      id: '/cursos/junior/'
      path: '/'
      fullPath: '/cursos/junior/'
      preLoaderRoute: typeof CursosJuniorIndexRouteImport
      parentRoute: typeof CursosJuniorRoute
    }
    '/cursos/junior/5-6-anos': {
      id: '/cursos/junior/5-6-anos'
      path: '/5-6-anos'
      fullPath: '/cursos/junior/5-6-anos'
      preLoaderRoute: typeof CursosJunior56AnosRouteImport
      parentRoute: typeof CursosJuniorRoute
    }
    '/cursos/junior/6-7-anos': {
      id: '/cursos/junior/6-7-anos'
      path: '/6-7-anos'
      fullPath: '/cursos/junior/6-7-anos'
      preLoaderRoute: typeof CursosJunior67AnosRouteImport
      parentRoute: typeof CursosJuniorRoute
    }
    '/cursos/junior/7-8-anos': {
      id: '/cursos/junior/7-8-anos'
      path: '/7-8-anos'
      fullPath: '/cursos/junior/7-8-anos'
      preLoaderRoute: typeof CursosJunior78AnosRouteImport
      parentRoute: typeof CursosJuniorRoute
    }
    '/particular/cursos/ads': {
      id: '/particular/cursos/ads'
      path: '/cursos/ads'
      fullPath: '/particular/cursos/ads'
      preLoaderRoute: typeof ParticularCursosAdsRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/agentes-ia': {
      id: '/particular/cursos/agentes-ia'
      path: '/cursos/agentes-ia'
      fullPath: '/particular/cursos/agentes-ia'
      preLoaderRoute: typeof ParticularCursosAgentesIaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/autocad': {
      id: '/particular/cursos/autocad'
      path: '/cursos/autocad'
      fullPath: '/particular/cursos/autocad'
      preLoaderRoute: typeof ParticularCursosAutocadRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/backend': {
      id: '/particular/cursos/backend'
      path: '/cursos/backend'
      fullPath: '/particular/cursos/backend'
      preLoaderRoute: typeof ParticularCursosBackendRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/canva': {
      id: '/particular/cursos/canva'
      path: '/cursos/canva'
      fullPath: '/particular/cursos/canva'
      preLoaderRoute: typeof ParticularCursosCanvaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/capcut': {
      id: '/particular/cursos/capcut'
      path: '/cursos/capcut'
      fullPath: '/particular/cursos/capcut'
      preLoaderRoute: typeof ParticularCursosCapcutRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/chatgpt': {
      id: '/particular/cursos/chatgpt'
      path: '/cursos/chatgpt'
      fullPath: '/particular/cursos/chatgpt'
      preLoaderRoute: typeof ParticularCursosChatgptRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/ciberseguranca': {
      id: '/particular/cursos/ciberseguranca'
      path: '/cursos/ciberseguranca'
      fullPath: '/particular/cursos/ciberseguranca'
      preLoaderRoute: typeof ParticularCursosCibersegurancaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/conteudo-ia': {
      id: '/particular/cursos/conteudo-ia'
      path: '/cursos/conteudo-ia'
      fullPath: '/particular/cursos/conteudo-ia'
      preLoaderRoute: typeof ParticularCursosConteudoIaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/copywriting': {
      id: '/particular/cursos/copywriting'
      path: '/cursos/copywriting'
      fullPath: '/particular/cursos/copywriting'
      preLoaderRoute: typeof ParticularCursosCopywritingRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/davinci': {
      id: '/particular/cursos/davinci'
      path: '/cursos/davinci'
      fullPath: '/particular/cursos/davinci'
      preLoaderRoute: typeof ParticularCursosDavinciRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/ecommerce': {
      id: '/particular/cursos/ecommerce'
      path: '/cursos/ecommerce'
      fullPath: '/particular/cursos/ecommerce'
      preLoaderRoute: typeof ParticularCursosEcommerceRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/excel': {
      id: '/particular/cursos/excel'
      path: '/cursos/excel'
      fullPath: '/particular/cursos/excel'
      preLoaderRoute: typeof ParticularCursosExcelRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/excel-ia': {
      id: '/particular/cursos/excel-ia'
      path: '/cursos/excel-ia'
      fullPath: '/particular/cursos/excel-ia'
      preLoaderRoute: typeof ParticularCursosExcelIaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/excel-power-bi': {
      id: '/particular/cursos/excel-power-bi'
      path: '/cursos/excel-power-bi'
      fullPath: '/particular/cursos/excel-power-bi'
      preLoaderRoute: typeof ParticularCursosExcelPowerBiRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/frontend': {
      id: '/particular/cursos/frontend'
      path: '/cursos/frontend'
      fullPath: '/particular/cursos/frontend'
      preLoaderRoute: typeof ParticularCursosFrontendRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/fullstack': {
      id: '/particular/cursos/fullstack'
      path: '/cursos/fullstack'
      fullPath: '/particular/cursos/fullstack'
      preLoaderRoute: typeof ParticularCursosFullstackRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/funil-vendas': {
      id: '/particular/cursos/funil-vendas'
      path: '/cursos/funil-vendas'
      fullPath: '/particular/cursos/funil-vendas'
      preLoaderRoute: typeof ParticularCursosFunilVendasRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/git': {
      id: '/particular/cursos/git'
      path: '/cursos/git'
      fullPath: '/particular/cursos/git'
      preLoaderRoute: typeof ParticularCursosGitRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/google-ads': {
      id: '/particular/cursos/google-ads'
      path: '/cursos/google-ads'
      fullPath: '/particular/cursos/google-ads'
      preLoaderRoute: typeof ParticularCursosGoogleAdsRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/ia': {
      id: '/particular/cursos/ia'
      path: '/cursos/ia'
      fullPath: '/particular/cursos/ia'
      preLoaderRoute: typeof ParticularCursosIaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/ia-visual': {
      id: '/particular/cursos/ia-visual'
      path: '/cursos/ia-visual'
      fullPath: '/particular/cursos/ia-visual'
      preLoaderRoute: typeof ParticularCursosIaVisualRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/impressao-3d': {
      id: '/particular/cursos/impressao-3d'
      path: '/cursos/impressao-3d'
      fullPath: '/particular/cursos/impressao-3d'
      preLoaderRoute: typeof ParticularCursosImpressao3dRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/informatica': {
      id: '/particular/cursos/informatica'
      path: '/cursos/informatica'
      fullPath: '/particular/cursos/informatica'
      preLoaderRoute: typeof ParticularCursosInformaticaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/jogos': {
      id: '/particular/cursos/jogos'
      path: '/cursos/jogos'
      fullPath: '/particular/cursos/jogos'
      preLoaderRoute: typeof ParticularCursosJogosRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/linux': {
      id: '/particular/cursos/linux'
      path: '/cursos/linux'
      fullPath: '/particular/cursos/linux'
      preLoaderRoute: typeof ParticularCursosLinuxRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/logica': {
      id: '/particular/cursos/logica'
      path: '/cursos/logica'
      fullPath: '/particular/cursos/logica'
      preLoaderRoute: typeof ParticularCursosLogicaRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/make': {
      id: '/particular/cursos/make'
      path: '/cursos/make'
      fullPath: '/particular/cursos/make'
      preLoaderRoute: typeof ParticularCursosMakeRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/manutencao': {
      id: '/particular/cursos/manutencao'
      path: '/cursos/manutencao'
      fullPath: '/particular/cursos/manutencao'
      preLoaderRoute: typeof ParticularCursosManutencaoRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/marketing': {
      id: '/particular/cursos/marketing'
      path: '/cursos/marketing'
      fullPath: '/particular/cursos/marketing'
      preLoaderRoute: typeof ParticularCursosMarketingRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/meta-ads': {
      id: '/particular/cursos/meta-ads'
      path: '/cursos/meta-ads'
      fullPath: '/particular/cursos/meta-ads'
      preLoaderRoute: typeof ParticularCursosMetaAdsRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/mobile': {
      id: '/particular/cursos/mobile'
      path: '/cursos/mobile'
      fullPath: '/particular/cursos/mobile'
      preLoaderRoute: typeof ParticularCursosMobileRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/modelagem-3d': {
      id: '/particular/cursos/modelagem-3d'
      path: '/cursos/modelagem-3d'
      fullPath: '/particular/cursos/modelagem-3d'
      preLoaderRoute: typeof ParticularCursosModelagem3dRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/n8n': {
      id: '/particular/cursos/n8n'
      path: '/cursos/n8n'
      fullPath: '/particular/cursos/n8n'
      preLoaderRoute: typeof ParticularCursosN8nRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/office': {
      id: '/particular/cursos/office'
      path: '/cursos/office'
      fullPath: '/particular/cursos/office'
      preLoaderRoute: typeof ParticularCursosOfficeRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/photoshop': {
      id: '/particular/cursos/photoshop'
      path: '/cursos/photoshop'
      fullPath: '/particular/cursos/photoshop'
      preLoaderRoute: typeof ParticularCursosPhotoshopRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/power-apps': {
      id: '/particular/cursos/power-apps'
      path: '/cursos/power-apps'
      fullPath: '/particular/cursos/power-apps'
      preLoaderRoute: typeof ParticularCursosPowerAppsRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/power-bi': {
      id: '/particular/cursos/power-bi'
      path: '/cursos/power-bi'
      fullPath: '/particular/cursos/power-bi'
      preLoaderRoute: typeof ParticularCursosPowerBiRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/powerpoint': {
      id: '/particular/cursos/powerpoint'
      path: '/cursos/powerpoint'
      fullPath: '/particular/cursos/powerpoint'
      preLoaderRoute: typeof ParticularCursosPowerpointRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/premiere': {
      id: '/particular/cursos/premiere'
      path: '/cursos/premiere'
      fullPath: '/particular/cursos/premiere'
      preLoaderRoute: typeof ParticularCursosPremiereRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/python': {
      id: '/particular/cursos/python'
      path: '/cursos/python'
      fullPath: '/particular/cursos/python'
      preLoaderRoute: typeof ParticularCursosPythonRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/python-apis': {
      id: '/particular/cursos/python-apis'
      path: '/cursos/python-apis'
      fullPath: '/particular/cursos/python-apis'
      preLoaderRoute: typeof ParticularCursosPythonApisRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/rag': {
      id: '/particular/cursos/rag'
      path: '/cursos/rag'
      fullPath: '/particular/cursos/rag'
      preLoaderRoute: typeof ParticularCursosRagRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/redes': {
      id: '/particular/cursos/redes'
      path: '/cursos/redes'
      fullPath: '/particular/cursos/redes'
      preLoaderRoute: typeof ParticularCursosRedesRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/redes-sociais': {
      id: '/particular/cursos/redes-sociais'
      path: '/cursos/redes-sociais'
      fullPath: '/particular/cursos/redes-sociais'
      preLoaderRoute: typeof ParticularCursosRedesSociaisRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/revit': {
      id: '/particular/cursos/revit'
      path: '/cursos/revit'
      fullPath: '/particular/cursos/revit'
      preLoaderRoute: typeof ParticularCursosRevitRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/seo': {
      id: '/particular/cursos/seo'
      path: '/cursos/seo'
      fullPath: '/particular/cursos/seo'
      preLoaderRoute: typeof ParticularCursosSeoRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/sql': {
      id: '/particular/cursos/sql'
      path: '/cursos/sql'
      fullPath: '/particular/cursos/sql'
      preLoaderRoute: typeof ParticularCursosSqlRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/suporte': {
      id: '/particular/cursos/suporte'
      path: '/cursos/suporte'
      fullPath: '/particular/cursos/suporte'
      preLoaderRoute: typeof ParticularCursosSuporteRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/tiktok-ads': {
      id: '/particular/cursos/tiktok-ads'
      path: '/cursos/tiktok-ads'
      fullPath: '/particular/cursos/tiktok-ads'
      preLoaderRoute: typeof ParticularCursosTiktokAdsRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/typescript': {
      id: '/particular/cursos/typescript'
      path: '/cursos/typescript'
      fullPath: '/particular/cursos/typescript'
      preLoaderRoute: typeof ParticularCursosTypescriptRouteImport
      parentRoute: typeof ParticularRoute
    }
    '/particular/cursos/word': {
      id: '/particular/cursos/word'
      path: '/cursos/word'
      fullPath: '/particular/cursos/word'
      preLoaderRoute: typeof ParticularCursosWordRouteImport
      parentRoute: typeof ParticularRoute
    }
  }
}

interface CursosCreateRouteChildren {
  CursosCreate1011AnosRoute: typeof CursosCreate1011AnosRoute
  CursosCreate1112AnosRoute: typeof CursosCreate1112AnosRoute
  CursosCreate1213AnosRoute: typeof CursosCreate1213AnosRoute
  CursosCreate1314AnosRoute: typeof CursosCreate1314AnosRoute
  CursosCreate89AnosRoute: typeof CursosCreate89AnosRoute
  CursosCreate910AnosRoute: typeof CursosCreate910AnosRoute
  CursosCreateIndexRoute: typeof CursosCreateIndexRoute
}

const CursosCreateRouteChildren: CursosCreateRouteChildren = {
  CursosCreate1011AnosRoute: CursosCreate1011AnosRoute,
  CursosCreate1112AnosRoute: CursosCreate1112AnosRoute,
  CursosCreate1213AnosRoute: CursosCreate1213AnosRoute,
  CursosCreate1314AnosRoute: CursosCreate1314AnosRoute,
  CursosCreate89AnosRoute: CursosCreate89AnosRoute,
  CursosCreate910AnosRoute: CursosCreate910AnosRoute,
  CursosCreateIndexRoute: CursosCreateIndexRoute,
}

const CursosCreateRouteWithChildren = CursosCreateRoute._addFileChildren(
  CursosCreateRouteChildren,
)

interface CursosJuniorRouteChildren {
  CursosJunior56AnosRoute: typeof CursosJunior56AnosRoute
  CursosJunior67AnosRoute: typeof CursosJunior67AnosRoute
  CursosJunior78AnosRoute: typeof CursosJunior78AnosRoute
  CursosJuniorIndexRoute: typeof CursosJuniorIndexRoute
}

const CursosJuniorRouteChildren: CursosJuniorRouteChildren = {
  CursosJunior56AnosRoute: CursosJunior56AnosRoute,
  CursosJunior67AnosRoute: CursosJunior67AnosRoute,
  CursosJunior78AnosRoute: CursosJunior78AnosRoute,
  CursosJuniorIndexRoute: CursosJuniorIndexRoute,
}

const CursosJuniorRouteWithChildren = CursosJuniorRoute._addFileChildren(
  CursosJuniorRouteChildren,
)

interface CursosRouteChildren {
  CursosAcademiesRoute: typeof CursosAcademiesRoute
  CursosCampsRoute: typeof CursosCampsRoute
  CursosCreateRoute: typeof CursosCreateRouteWithChildren
  CursosJuniorRoute: typeof CursosJuniorRouteWithChildren
  CursosIndexRoute: typeof CursosIndexRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosAcademiesRoute: CursosAcademiesRoute,
  CursosCampsRoute: CursosCampsRoute,
  CursosCreateRoute: CursosCreateRouteWithChildren,
  CursosJuniorRoute: CursosJuniorRouteWithChildren,
  CursosIndexRoute: CursosIndexRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

interface ParticularRouteChildren {
  ParticularIndexRoute: typeof ParticularIndexRoute
  ParticularCursosAdsRoute: typeof ParticularCursosAdsRoute
  ParticularCursosAgentesIaRoute: typeof ParticularCursosAgentesIaRoute
  ParticularCursosAutocadRoute: typeof ParticularCursosAutocadRoute
  ParticularCursosBackendRoute: typeof ParticularCursosBackendRoute
  ParticularCursosCanvaRoute: typeof ParticularCursosCanvaRoute
  ParticularCursosCapcutRoute: typeof ParticularCursosCapcutRoute
  ParticularCursosChatgptRoute: typeof ParticularCursosChatgptRoute
  ParticularCursosCibersegurancaRoute: typeof ParticularCursosCibersegurancaRoute
  ParticularCursosConteudoIaRoute: typeof ParticularCursosConteudoIaRoute
  ParticularCursosCopywritingRoute: typeof ParticularCursosCopywritingRoute
  ParticularCursosDavinciRoute: typeof ParticularCursosDavinciRoute
  ParticularCursosEcommerceRoute: typeof ParticularCursosEcommerceRoute
  ParticularCursosExcelRoute: typeof ParticularCursosExcelRoute
  ParticularCursosExcelIaRoute: typeof ParticularCursosExcelIaRoute
  ParticularCursosExcelPowerBiRoute: typeof ParticularCursosExcelPowerBiRoute
  ParticularCursosFrontendRoute: typeof ParticularCursosFrontendRoute
  ParticularCursosFullstackRoute: typeof ParticularCursosFullstackRoute
  ParticularCursosFunilVendasRoute: typeof ParticularCursosFunilVendasRoute
  ParticularCursosGitRoute: typeof ParticularCursosGitRoute
  ParticularCursosGoogleAdsRoute: typeof ParticularCursosGoogleAdsRoute
  ParticularCursosIaRoute: typeof ParticularCursosIaRoute
  ParticularCursosIaVisualRoute: typeof ParticularCursosIaVisualRoute
  ParticularCursosImpressao3dRoute: typeof ParticularCursosImpressao3dRoute
  ParticularCursosInformaticaRoute: typeof ParticularCursosInformaticaRoute
  ParticularCursosJogosRoute: typeof ParticularCursosJogosRoute
  ParticularCursosLinuxRoute: typeof ParticularCursosLinuxRoute
  ParticularCursosLogicaRoute: typeof ParticularCursosLogicaRoute
  ParticularCursosMakeRoute: typeof ParticularCursosMakeRoute
  ParticularCursosManutencaoRoute: typeof ParticularCursosManutencaoRoute
  ParticularCursosMarketingRoute: typeof ParticularCursosMarketingRoute
  ParticularCursosMetaAdsRoute: typeof ParticularCursosMetaAdsRoute
  ParticularCursosMobileRoute: typeof ParticularCursosMobileRoute
  ParticularCursosModelagem3dRoute: typeof ParticularCursosModelagem3dRoute
  ParticularCursosN8nRoute: typeof ParticularCursosN8nRoute
  ParticularCursosOfficeRoute: typeof ParticularCursosOfficeRoute
  ParticularCursosPhotoshopRoute: typeof ParticularCursosPhotoshopRoute
  ParticularCursosPowerAppsRoute: typeof ParticularCursosPowerAppsRoute
  ParticularCursosPowerBiRoute: typeof ParticularCursosPowerBiRoute
  ParticularCursosPowerpointRoute: typeof ParticularCursosPowerpointRoute
  ParticularCursosPremiereRoute: typeof ParticularCursosPremiereRoute
  ParticularCursosPythonRoute: typeof ParticularCursosPythonRoute
  ParticularCursosPythonApisRoute: typeof ParticularCursosPythonApisRoute
  ParticularCursosRagRoute: typeof ParticularCursosRagRoute
  ParticularCursosRedesRoute: typeof ParticularCursosRedesRoute
  ParticularCursosRedesSociaisRoute: typeof ParticularCursosRedesSociaisRoute
  ParticularCursosRevitRoute: typeof ParticularCursosRevitRoute
  ParticularCursosSeoRoute: typeof ParticularCursosSeoRoute
  ParticularCursosSqlRoute: typeof ParticularCursosSqlRoute
  ParticularCursosSuporteRoute: typeof ParticularCursosSuporteRoute
  ParticularCursosTiktokAdsRoute: typeof ParticularCursosTiktokAdsRoute
  ParticularCursosTypescriptRoute: typeof ParticularCursosTypescriptRoute
  ParticularCursosWordRoute: typeof ParticularCursosWordRoute
}

const ParticularRouteChildren: ParticularRouteChildren = {
  ParticularIndexRoute: ParticularIndexRoute,
  ParticularCursosAdsRoute: ParticularCursosAdsRoute,
  ParticularCursosAgentesIaRoute: ParticularCursosAgentesIaRoute,
  ParticularCursosAutocadRoute: ParticularCursosAutocadRoute,
  ParticularCursosBackendRoute: ParticularCursosBackendRoute,
  ParticularCursosCanvaRoute: ParticularCursosCanvaRoute,
  ParticularCursosCapcutRoute: ParticularCursosCapcutRoute,
  ParticularCursosChatgptRoute: ParticularCursosChatgptRoute,
  ParticularCursosCibersegurancaRoute: ParticularCursosCibersegurancaRoute,
  ParticularCursosConteudoIaRoute: ParticularCursosConteudoIaRoute,
  ParticularCursosCopywritingRoute: ParticularCursosCopywritingRoute,
  ParticularCursosDavinciRoute: ParticularCursosDavinciRoute,
  ParticularCursosEcommerceRoute: ParticularCursosEcommerceRoute,
  ParticularCursosExcelRoute: ParticularCursosExcelRoute,
  ParticularCursosExcelIaRoute: ParticularCursosExcelIaRoute,
  ParticularCursosExcelPowerBiRoute: ParticularCursosExcelPowerBiRoute,
  ParticularCursosFrontendRoute: ParticularCursosFrontendRoute,
  ParticularCursosFullstackRoute: ParticularCursosFullstackRoute,
  ParticularCursosFunilVendasRoute: ParticularCursosFunilVendasRoute,
  ParticularCursosGitRoute: ParticularCursosGitRoute,
  ParticularCursosGoogleAdsRoute: ParticularCursosGoogleAdsRoute,
  ParticularCursosIaRoute: ParticularCursosIaRoute,
  ParticularCursosIaVisualRoute: ParticularCursosIaVisualRoute,
  ParticularCursosImpressao3dRoute: ParticularCursosImpressao3dRoute,
  ParticularCursosInformaticaRoute: ParticularCursosInformaticaRoute,
  ParticularCursosJogosRoute: ParticularCursosJogosRoute,
  ParticularCursosLinuxRoute: ParticularCursosLinuxRoute,
  ParticularCursosLogicaRoute: ParticularCursosLogicaRoute,
  ParticularCursosMakeRoute: ParticularCursosMakeRoute,
  ParticularCursosManutencaoRoute: ParticularCursosManutencaoRoute,
  ParticularCursosMarketingRoute: ParticularCursosMarketingRoute,
  ParticularCursosMetaAdsRoute: ParticularCursosMetaAdsRoute,
  ParticularCursosMobileRoute: ParticularCursosMobileRoute,
  ParticularCursosModelagem3dRoute: ParticularCursosModelagem3dRoute,
  ParticularCursosN8nRoute: ParticularCursosN8nRoute,
  ParticularCursosOfficeRoute: ParticularCursosOfficeRoute,
  ParticularCursosPhotoshopRoute: ParticularCursosPhotoshopRoute,
  ParticularCursosPowerAppsRoute: ParticularCursosPowerAppsRoute,
  ParticularCursosPowerBiRoute: ParticularCursosPowerBiRoute,
  ParticularCursosPowerpointRoute: ParticularCursosPowerpointRoute,
  ParticularCursosPremiereRoute: ParticularCursosPremiereRoute,
  ParticularCursosPythonRoute: ParticularCursosPythonRoute,
  ParticularCursosPythonApisRoute: ParticularCursosPythonApisRoute,
  ParticularCursosRagRoute: ParticularCursosRagRoute,
  ParticularCursosRedesRoute: ParticularCursosRedesRoute,
  ParticularCursosRedesSociaisRoute: ParticularCursosRedesSociaisRoute,
  ParticularCursosRevitRoute: ParticularCursosRevitRoute,
  ParticularCursosSeoRoute: ParticularCursosSeoRoute,
  ParticularCursosSqlRoute: ParticularCursosSqlRoute,
  ParticularCursosSuporteRoute: ParticularCursosSuporteRoute,
  ParticularCursosTiktokAdsRoute: ParticularCursosTiktokAdsRoute,
  ParticularCursosTypescriptRoute: ParticularCursosTypescriptRoute,
  ParticularCursosWordRoute: ParticularCursosWordRoute,
}

const ParticularRouteWithChildren = ParticularRoute._addFileChildren(
  ParticularRouteChildren,
)

interface SobreRouteChildren {
  SobreVisaoRoute: typeof SobreVisaoRoute
  SobreIndexRoute: typeof SobreIndexRoute
}

const SobreRouteChildren: SobreRouteChildren = {
  SobreVisaoRoute: SobreVisaoRoute,
  SobreIndexRoute: SobreIndexRoute,
}

const SobreRouteWithChildren = SobreRoute._addFileChildren(SobreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRouteWithChildren,
  LinksRoute: LinksRoute,
  ParticularRoute: ParticularRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRouteWithChildren,
  TermosRoute: TermosRoute,
  ApresentacoesInformaticaCreateRoute: ApresentacoesInformaticaCreateRoute,
  ApresentacoesInformaticaJuniorRoute: ApresentacoesInformaticaJuniorRoute,
  ApresentacoesTecnologiaCreateRoute: ApresentacoesTecnologiaCreateRoute,
  ApresentacoesTecnologiaJuniorRoute: ApresentacoesTecnologiaJuniorRoute,
  ProfessoresInformaticaCreateRoute: ProfessoresInformaticaCreateRoute,
  ProfessoresInformaticaJuniorRoute: ProfessoresInformaticaJuniorRoute,
  ProfessoresTecnologiaCreateRoute: ProfessoresTecnologiaCreateRoute,
  ProfessoresTecnologiaJuniorRoute: ProfessoresTecnologiaJuniorRoute,
  ApresentacoesIndexRoute: ApresentacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
